### ISSUE TITLE
How to calculate parameters and flops

### ISSUE THREAD

**Issue by SanmAIGO** [SLDGroup/CASCADE#3]
I have a problem in calculating the parameters and flops. Can you give me the parameters and flops of the two models?

**Comment by SanmAIGO** [comment]
Hello, your work is excellent, but I want to know the parameters and FLOPS of TransCASCADE and PVTCASCADE that you proposed in your paper? Or can you implement the calculation method?

**Comment by mostafij-rahman** [comment]
Hi, 

We appreciate your feedback. Our PVT-CASCADE has 34.13M params and 5.84G FLOPS. You can try to get stats of TransCASCADE using 'get_model_complexity_info' function from the python 'ptflops' or some other similar libraries.

Best,
Mostafij

**Comment by SanmAIGO** [comment]
> 

Thank you for your reply. I used from ptflops importget _ model _ complexity _ info for TransCASCADE.
macs, params = get_model_complexity_info(net, (3, args.img_size, args.img_size), as_strings=True,
print_per_layer_stat=False, verbose=True)
print('{:<30}  {:<8}'.format('Computational complexity: ', macs))
print('{:<30}  {:<8}'.format('Number of parameters: ', params))
But I got the following error.
Traceback (most recent call last):
File "E:/Program Files/JetBrains/PyCharm 2022.3.2/plugins/python/helpers/pydev/pydevd.py", line 1496, in _exec
pydev_imports.execfile(file, globals, locals)  # execute the script
File "E:\Program Files\JetBrains\PyCharm 2022.3.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
exec(compile(contents+"\n", file, 'exec'), glob, loc)
File "D:\WorkSpace\Pycharm\Parameter\CASCADE-main\train_synapse.py", line 101, in <module>
macs, params = get_model_complexity_info(net, (3, args.img_size, args.img_size), as_strings=True,
File "E:\DeepLearning\anaconda3\envs\TI11\lib\site-packages\ptflops\flops_counter.py", line 30, in get_model_complexity_info
flops_count, params_count = get_flops_pytorch(model, input_res,
File "E:\DeepLearning\anaconda3\envs\TI11\lib\site-packages\ptflops\pytorch_engine.py", line 46, in get_flops_pytorch
flops_count, params_count = flops_model.compute_average_flops_cost()
File "E:\DeepLearning\anaconda3\envs\TI11\lib\site-packages\ptflops\pytorch_engine.py", line 152, in compute_average_flops_cost
flops_sum = self.accumulate_flops()
File "E:\DeepLearning\anaconda3\envs\TI11\lib\site-packages\ptflops\pytorch_engine.py", line 69, in accumulate_flops
sum += m.accumulate_flops()
File "E:\DeepLearning\anaconda3\envs\TI11\lib\site-packages\ptflops\pytorch_engine.py", line 69, in accumulate_flops
sum += m.accumulate_flops()
File "E:\DeepLearning\anaconda3\envs\TI11\lib\site-packages\ptflops\pytorch_engine.py", line 69, in accumulate_flops
sum += m.accumulate_flops()
File "E:\DeepLearning\anaconda3\envs\TI11\lib\site-packages\ptflops\pytorch_engine.py", line 65, in accumulate_flops
return self.__flops__
File "E:\DeepLearning\anaconda3\envs\TI11\lib\site-packages\torch\nn\modules\module.py", line 1185, in __getattr__
raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Conv2d' object has no attribute '__flops__'

Process finished with exit code 1
This makes me very upset.

**Comment by SanmAIGO** [comment]
> Hi,
> 
> We appreciate your feedback. Our PVT-CASCADE has 34.13M params and 5.84G FLOPS. You can try to get stats of TransCASCADE using 'get_model_complexity_info' function from the python 'ptflops' or some other similar libraries.
> 
> Best, Mostafij
Hello！Mr. Mostafij
If it is convenient for you, can you tell me the parameters and FLOPS of TransCASCADE? Thank you for your selfless sharing.
Best
Sanm
